<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\URL;

class Center extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $listCenter = $this->listCenter();
        $faker = \Faker\Factory::create();
        for ($i = 50; $i < 100; $i++) {
            DB::table('english_center')->insert([
                'user_id' => $i,
                'name' => $listCenter[array_rand($listCenter)],
                'email' => $faker->email,
                'address' => $faker->address,
                'phone_number' => $faker->phoneNumber,
                'website' => 'test.com',
                'avatar' => 'center.jpeg',
                'description' => $faker->text,
                'area_id' => rand(1, 5),
                'ave_star' => rand(1, 5),
                'status' => 1,
                'created_at' => $faker->dateTime,
            ]);
        }
    }

    public function listCenter()
    {
        return [
            0 => "Trung Tâm Tiếng Anh CES ",
            1 => "Nền tảng học tiếng Anh online 1-1 Kidtopi ",
            2 => "Trường Anh Ngữ Quốc Tế Clever Academy ",
            3 => "Trung Tâm Anh Ngữ Aroma - Tiếng Anh Cho Người Đi Làm ",
            4 => "Trung tâm Anh ngữ E4U ",
            5 => "Học Viện IvyPrep ",
            6 => "Trung tâm Anh ngữ Elingo IELTS ",
            7 => "Trung Tâm Anh Ngữ Cleverlearn ",
            8 => "Trung Tâm Luyện Thi Ielts Fighter ",
            9 => "Trung Tâm Language Link Vietnam ",
            10 => "Trung tâm anh ngữ ESOLD ",
            11 => "Trung Tâm Du Học Philippines PHILENGLISH ",
            12 => "Trung tâm Anh ngữ Sedu English ",
            13 => "Trung tâm AMATE English ",
            14 => "Học viện Đào tạo tiếng Anh và Kỹ năng Impactus ",
            15 => "Anh Ngữ Quốc Tế AMES ",
            16 => "Học viện Anh ngữ EQuest EQuest Academy ",
            17 => "Trung tâm Anh ngữ TES - Thầy Jimmy ",
            18 => "Tiếng Anh 123 ",
            19 => "Trung tâm Anh ngữ Jaxtina ",
            20 => "Trung Tâm Anh Ngữ Quốc Tế American Links ",
            21 => "Trung Tâm Anh Ngữ English Camp ",
            22 => "Trung Tâm Tiếng Anh CES ",
            23 => "Nền tảng học tiếng Anh online 1-1 Kidtopi ",
            24 => "Trung Tâm Du Học SET ",
            25 => "Trung Tâm Ngoại Ngữ Toeic Hà Nội ",
            26 => "Trung Tâm Tiếng Anh Anh Thầy ",
            27 => "Trung tâm TOEFL cô Giang ",
            28 => "Trung Tâm Anh Ngữ Apollo 360 ",
            29 => "Trung tâm Anh ngữ Headstart Vietnam ",
            30 => "Trung Tâm Ngoại Ngữ Multi Language ",
            31 => "Trung tâm du học và đào tạo ngoại ngữ Jelly Education ",
            32 => "Trung tâm học tiếng Anh online - Elight ",
            33 => "Trung Tâm Giáo Dục và Đào Tạo Pathways ",
            34 => "Trung Tâm Tiếng Anh NewLight ",
            35 => "Trung Tâm Anh Ngữ TAPL ",
            36 => "Trung Tâm Ngoại Ngữ Wider World ",
            37 => "Trung tâm tiếng anh English Beyond Education ",
            38 => "Trung Tâm Tiếng Anh GEEKO ",
            39 => "Trung Tâm Anh Ngữ Ms Phương ",
            40 => "Trung Tâm IELTS Cô Mai Lai ",
            41 => "Trung Tâm IELTS Cô Nhã ",
            42 => "Trung Tâm Anh Ngữ Bright Way ",
            43 => "Trung Tâm Tiếng Anh Nam Anh ",
            44 => "VietPhil Education Group ",
            45 => "Trung tâm Anh ngữ BST - Big Step Training ",
            46 => "Trung Tâm Anh Ngữ Mamita ",
            47 => "Trung Tâm Princeton English ",
            48 => "Trung tâm OSB STEAM English ",
            49 => "Trung tâm Anh ngữ Quốc tế D&C ",
            50 => "Trung tâm Anh ngữ Cambridge IEC ",
            51 => "Trung tâm Anh ngữ Learn4Life ",
            52 => "Trung tâm Nhật ngữ Nagomi ",
            53 => "Trung tâm Solar English ",
            54 => "Trung tâm Anh ngữ trẻ em Takus ",
            55 => "Trung tâm Anh ngữ New Era ",
            56 => "Trung tâm Anh ngữ Nuin Education ",
            57 => "Trung tâm Anh ngữ Linkee ",
            58 => "Trung tâm Anh ngữ Quốc tế Espeed ",
            59 => "Trung tâm Ngoại ngữ Phương Đông ",
            60 => "Trung tâm OSB STEAM English ",
            61 => "Trung tâm Anh ngữ Quốc tế D&C ",
            62 => "Trung tâm Anh ngữ Cambridge IEC ",
            63 => "Trung tâm Anh ngữ Learn4Life ",
            64 => "Trung tâm Nhật ngữ Nagomi ",
            65 => "Trung tâm Solar English ",
            66 => "Trung tâm Anh ngữ trẻ em Takus ",
            67 => "Trung tâm Anh ngữ New Era ",
            68 => "Trung tâm Anh ngữ Nuin Education ",
            69 => "Trung tâm Anh ngữ Linkee ",
            70 => "Trung tâm Anh ngữ Quốc tế Espeed ",
            71 => "Trung tâm Ngoại ngữ Phương Đông ",
            72 => "Trung Tâm English House ",
            73 => "Trung Tâm Tiếng Anh Elite ",
            74 => "Trung Tâm Anh Ngữ London ",
            75 => "Trung Tâm Học Tiếng Anh Trực Tuyến Homeclass ",
            76 => "Trung Tâm Dream House ",
            77 => "Trung tâm tiếng anh Tree ",
            78 => "Trung tâm tiếng Anh ATZ ",
            79 => "Trung tâm Talk Talk English ",
            80 => "Trung Tâm Anh Ngữ Bestway ",
            81 => "Trung Tâm Tiếng Anh H&H ",
            82 => "Trung Tâm Ngoại Ngữ Viet Advance ",
            83 => "Trung tâm tiếng Nhật Hikari ",
            84 => "Trung tâm Anh ngữ SLINK ",
            85 => "Trung tâm Anh ngữ Vicare ",
            86 => "Trung tâm Ngoại ngữ Up On ",
            87 => "Trung tâm Anh ngữ Quốc tế NEMO ",
            88 => "Trung tâm Anh ngữ Việt-Úc ",
            89 => "Trung tâm Anh ngữ Tâm Việt IQ ",
            90 => "Trung tâm ETS Việt Đức ",
            91 => "Trung tâm đào tạo Ngoại ngữ Benjamin ",
            92 => "Trung tâm Ngoại ngữ Moose ",
            93 => "Trung tâm Ngoại ngữ - Du học Việt Thắng ",
            94 => "Trung tâm Anh ngữ Kids' Dream ",
            95 => "Trung tâm Anh ngữ Big Star ",
            96 => "Trung Tâm Ngoại Ngữ Just Kids ",
            97 => "Trung Tâm Anh Ngữ Mika ",
            98 => "Trung Tâm May School ",
            99 => "Trung Tâm BenBen Foreign Language ",
            100 => "Trung Tâm RVi Hà Nội ",
            101 => "Trung Tâm IvyCation ",
            102 => "Popodoo Smart English ",
            103 => "Trung tâm Anh ngữ CLA ",
            104 => "Trung tâm kỹ năng anh ngữ Linkinworld ",
            105 => "Trung tâm anh ngữ L&D ",
            106 => "Trung tâm tiếng anh Roadmap ",
            107 => "Trung Tâm Tiếng Anh Grow Green ",
            108 => "Trung tâm tiếng Anh cô Hằng Bựa ",
            109 => "Trung Tâm Anh Ngữ Lê Nguyệt ",
            110 => "Học viện Giáo dục Quốc tế Elink Việt Nam ",
            111 => "Trung tâm Anh Ngữ Everest ",
            112 => "Trung Tâm Toeic Building ",
            113 => "Trung tâm anh ngữ UNIVER ",
            114 => "Trường ngoại ngữ Hà Nội ",
            115 => "Trung tâm tiếng Anh Hoangology ",
            116 => "Trung Tâm Anh Ngữ SmartLink ",
            117 => "Trung Tâm Anh Ngữ Joy School ",
            118 => "Trung Tâm Ngoại Ngữ Sunshine ",
            119 => "Trung Tâm Tiếng Anh ABBA ",
            120 => "Trường Ngoại ngữ Kiwi English ",
            121 => "Trung tâm Anh ngữ English Explorer ",
            122 => "Trung tâm tiếng Anh Loving English ",
            123 => "Trung tâm Ngoại ngữ Viettalent ",
            124 => "Trung tâm Anh ngữ Testlink ",
            125 => "Trung tâm Anh ngữ Quốc tế ECOLINK ",
            126 => "Trung tâm Ngoại ngữ Quốc tế Brainway ",
            127 => "Trung tâm Ngoại ngữ Quốc tế Diamond Star ",
            128 => "Trung tâm Go English ",
            129 => "Trung tâm tiếng Anh KiddyLand ",
            130 => "Trung tâm Anh ngữ Tin học Sydney ",
            131 => "Trung tâm Gitizen English ",
            132 => "Trường Anh Ngữ Quốc Tế APEC ",
            133 => "Trung Tâm Anh Ngữ Quốc Tế Shelton ",
            134 => "Trung Tâm Tiếng Anh Edumax ",
            135 => "Trung Tâm Ngoại Ngữ Hà Nội ",
            136 => "Trung Tâm Thầy Quý Tuấn TOEIC 990/990 ",
            137 => "Trung tâm IELTS Linh UK ",
            138 => "Trung Tâm Tiếng Anh 5epro ",
            139 => "Anh Ngữ Quốc Tế Educare ",
            140 => "Trung tâm ngoại ngữ Gee ",
            141 => "Trung Tâm Ngoại Ngữ Tiếng Anh LiLy ",
            142 => "Trung Tâm Anh Ngữ iSpeaking ",
            143 => "Hệ Thống Anh Ngữ Trẻ Em Vietchild ",
            144 => "Học viện Anh ngữ Clever Clogs ",
            145 => "Trung tâm Du học - Ngoại ngữ ITM ",
            146 => "Trung tâm Ngoại ngữ tin học E.Future ",
            147 => "Trung tâm đào tạo nhân lực PTM ",
            148 => "Trung tâm Tiếng Anh Western Ocean ",
            149 => "Trung tâm Anh ngữ ITD ",
            150 => "Trung tâm Anh ngữ Capitole ",
            151 => "Trung tâm Ngoại ngữ Eduline ",
            152 => "Trung tâm Ngoại ngữ Quốc tế HACIC ",
            153 => "Trung tâm Anh ngữ Sunkids",
        ];
    }
}
