<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataSeeder extends Seeder
{
    protected $firstName = array(
        'An', 'Anh',
        'Bào', 'Bình', 'Bạch', 'Bảo', 'Bắc', 'Bằng', 'Bổng', 'Bửu',
        'Ca', 'Canh', 'Chiến', 'Chiểu', 'Châu', 'Chính', 'Chương', 'Chưởng', 'Chấn', 'Công', 'Cơ', 'Cương', 'Cường', 'Cảnh', 'Cần', 'Cẩn',
        'Danh', 'Di', 'Dinh', 'Diệp', 'Diệu', 'Du', 'Duy', 'Duệ', 'Dân', 'Dũng', 'Dương', 'Dụng',
        'Giang', 'Giác', 'Giáp',
        'Hiên', 'Hiếu', 'Hiền', 'Hiển', 'Hiệp', 'Hoa', 'Hoài', 'Hoàn', 'Hoàng', 'Hoán', 'Huy', 'Huynh', 'Huấn', 'Huỳnh', 'Hà', 'Hành', 'Hào', 'Hòa', 'Hùng', 'Hưng', 'Hạnh', 'Hải', 'Hảo', 'Hậu', 'Học', 'Hồng', 'Hội', 'Hợp', 'Hữu', 'Hỷ',
        'Kha', 'Khang', 'Khanh', 'Khiêm', 'Khiếu', 'Khoa', 'Khoát', 'Khánh', 'Khôi', 'Khương', 'Khải', 'Kim', 'Kiên', 'Kiếm', 'Kiện', 'Kiệt', 'Kính', 'Kỳ', 'Kỷ',
        'Lai', 'Lam', 'Linh', 'Liêm', 'Long', 'Luận', 'Luật', 'Lâm', 'Lân', 'Lý', 'Lĩnh', 'Lương', 'Lạc', 'Lập', 'Lễ', 'Lộ', 'Lộc', 'Lực',
        'Minh', 'Mạnh', 'Mẫn', 'Mỹ',
        'Nam', 'Nghiêm', 'Nghiệp', 'Nghĩa', 'Nghị', 'Nguyên', 'Ngân', 'Ngôn', 'Ngạn', 'Ngọc', 'Nhiên', 'Nhu', 'Nhuận', 'Nhân', 'Nhã', 'Nhượng', 'Nhạn', 'Nhật', 'Ninh',
        'Phi', 'Phong', 'Pháp', 'Phát', 'Phú', 'Phúc', 'Phương', 'Phước', 'Phụng',
        'Quang', 'Quyết', 'Quyền', 'Quân', 'Quý', 'Quảng', 'Quế', 'Quốc', 'Quỳnh',
        'Sang', 'Sinh', 'Siêu', 'Sáng', 'Sâm', 'Sĩ', 'Sơn', 'Sử', 'Sỹ',
        'Thanh', 'Thiên', 'Thiện', 'Thuận', 'Thành', 'Thái', 'Thông', 'Thúc', 'Thạc', 'Thạch', 'Thắng', 'Thể', 'Thịnh', 'Thọ', 'Thống', 'Thời', 'Thụy', 'Thủy', 'Thực', 'Tiến', 'Tiếp', 'Tiền', 'Tiển', 'Toàn', 'Toại', 'Toản', 'Trang', 'Triết', 'Triều', 'Triệu', 'Trung', 'Trác', 'Tráng', 'Trân', 'Trình', 'Trí', 'Trúc', 'Trường', 'Trưởng', 'Trạch', 'Trọng', 'Trụ', 'Trực', 'Tuyền', 'Tuấn', 'Tuệ', 'Tài', 'Tâm', 'Tân', 'Tín', 'Tùng', 'Tú', 'Tường', 'Tấn', 'Tụ', 'Từ',
        'Uy',
        'Vinh', 'Viên', 'Việt', 'Vu', 'Võ', 'Văn', 'Vĩ', 'Vĩnh', 'Vũ', 'Vương', 'Vượng', 'Vịnh', 'Vỹ',
        'Xuân',
        'Yên',
        'Án', 'Ân',
        'Đan', 'Điền', 'Điệp', 'Đoàn', 'Đình', 'Đôn', 'Đăng', 'Đại', 'Đạo', 'Đạt', 'Định', 'Đồng', 'Độ', 'Đức', 'Đức',
        'Ẩn',
    );
    protected $middleName = array(
        'An', 'Anh',
        'Bá', 'Bách', 'Bình', 'Bích', 'Bảo', 'Bằng', 'Bửu', 'Bữu',
        'Cao', 'Chiêu', 'Chiến', 'Chung', 'Chuẩn', 'Chánh', 'Chí', 'Chính', 'Chấn', 'Chế', 'Cát', 'Công', 'Cương', 'Cường', 'Cảnh',
        'Danh', 'Duy', 'Dân', 'Dũng', 'Dương',
        'Gia', 'Giang',
        'Hiếu', 'Hiền', 'Hiểu', 'Hiệp', 'Hoài', 'Hoàn', 'Hoàng', 'Huy', 'Huân', 'Hà', 'Hào', 'Hán', 'Hòa', 'Hùng', 'Hưng', 'Hướng', 'Hạnh', 'Hạo', 'Hải', 'Hồ', 'Hồng', 'Hữu',
        'Khai', 'Khang', 'Khoa', 'Khuyến', 'Khánh', 'Khôi', 'Khương', 'Khải', 'Khắc', 'Khởi', 'Kim', 'Kiên', 'Kiến', 'Kiệt', 'Kỳ',
        'Lam', 'Liên', 'Long', 'Lâm', 'Lương', 'Lạc', 'Lập',
        'Minh', 'Mạnh', 'Mộng',
        'Nam', 'Nghĩa', 'Nghị', 'Nguyên', 'Nguyễn', 'Ngọc', 'Nhân', 'Như', 'Nhất', 'Nhật', 'Niệm',
        'Phi', 'Phong', 'Phú', 'Phúc', 'Phương', 'Phước', 'Phượng', 'Phục', 'Phụng',
        'Quang', 'Quyết', 'Quân', 'Quý', 'Quảng', 'Quốc',
        'Song', 'Sĩ', 'Sơn', 'Sỹ',
        'Tài', 'Tạ',
        'Ân',
        'Đan', 'Đinh', 'Đoàn', 'Đình', 'Đông', 'Đăng', 'Đại', 'Đạt', 'Đắc', 'Định', 'Đồng', 'Đức', 'Đăng', 'Đức',
    );
    protected $lastName = array(
        'An', 'Ánh',
        'Ân', 'Âu', 'Ấu',
        'Biện', 'Bàng', 'Bành', 'Bá', 'Bì', 'Bình', 'Bùi', 'Bạc', 'Bạch', 'Bảo', 'Bế', 'Bồ', 'Bửu',
        'Ca', 'Cam', 'Cao', 'Chiêm', 'Chu', 'Chung', 'Châu', 'Chương', 'Chế', 'Chử', 'Cung', 'Cái', 'Cát', 'Cù', 'Cấn', 'Cầm', 'Cổ', 'Cự',
        'Danh', 'Diêm', 'Diệp', 'Doãn', 'Dã', 'Dư', 'Dương',
        'Đan', 'Đàm', 'Đào', 'Đái', 'Đặng', 'Đậu', 'Đinh', 'Điền', 'Đoàn', 'Đôn', 'Đồng', 'Đổng', 'Đỗ', 'Đới', 'Đường',
        'Giang', 'Giao', 'Giáp', 'Giả',
        'Hoa', 'Hoàng', 'Huỳnh', 'Hy', 'Hà', 'Hàn', 'Hàng', 'Hán', 'Hình', 'Hùng', 'Hạ', 'Hồ', 'Hồng', 'Hứa',
        'Kha', 'Khoa', 'Khu', 'Khuất', 'Khâu', 'Khúc', 'Khưu', 'Khương', 'Khổng', 'Kim', 'Kiều',
        'La', 'Liễu', 'Lâm', 'Lã', 'Lê', 'Lò', 'Lô', 'Lý', 'Lư', 'Lưu', 'Lương', 'Lạc', 'Lại', 'Lều', 'Lỡ', 'Lục', 'Lữ', 'Lỳ',
        'Ma', 'Mai', 'Mang', 'Mâu', 'Mã', 'Mạc', 'Mạch', 'Mẫn', 'Mộc',
        'Nghiêm', 'Nghị', 'Nguyễn', 'Ngân', 'Ngô', 'Ngụy', 'Nhiệm', 'Nhâm', 'Nhậm', 'Nhữ', 'Ninh', 'Nông',
        'Ong',
        'Ông',
        'Phan', 'Phi', 'Phí', 'Phó', 'Phùng', 'Phương', 'Phạm',
        'Quách', 'Quản',
        'Sơn', 'Sử',
        'Thi', 'Thiều', 'Thào', 'Thái', 'Thân', 'Thôi', 'Thạch', 'Thập', 'Thịnh', 'Tiêu', 'Tiếp', 'Trang', 'Triệu', 'Trà', 'Trác', 'Trình', 'Trưng', 'Trương', 'Trần', 'Trịnh', 'Ty', 'Tào', 'Tòng', 'Tô', 'Tôn', 'Tông', 'Tăng', 'Tạ', 'Tống', 'Từ',
        'Ung', 'Uông',
        'Vi', 'Viên', 'Võ', 'Văn', 'Vũ', 'Vương', 'Vừ', 'Xa',
        'Yên',
    );
    protected $phoneNumber = [
        '0968055101', '0968054411', '09680557844', '0987852012', '0968845121', '0965444445', '09674512124', '09752354044', '097464984984', '097448445100', '09848005350', '09848465135', '09844654544', '09855116444'
    ];
    protected $address = array(
        'An Giang', 'Bà Rịa - Vũng Tàu',
        'Bắc Giang', 'Bắc Kạn', 'Bạc Liêu',
        'Bắc Ninh', 'Bến Tre', 'Bình Định',
        'Bình Dương', 'Bình Phước', 'Bình Thuận',
        'Cà Mau', 'Cao Bằng', 'Đắk Lắk',
        'Đắk Nông', 'Điện Biên', 'Đồng Nai',
        'Đồng Tháp', 'Gia Lai', 'Hà Giang',
        'Hà Nam', 'Hà Tĩnh', 'Hải Dương',
        'Hậu Giang', 'Hòa Bình', 'Hưng Yên',
        'Khánh Hòa', 'Kiên Giang', 'Kon Tum',
        'Lai Châu', 'Lâm Đồng', 'Lạng Sơn',
        'Lào Cai', 'Long An', 'Nam Định',
        'Nghệ An', 'Ninh Bình', 'Ninh Thuận',
        'Phú Thọ', 'Quảng Bình', 'Quảng Nam',
        'Quảng Ngãi', 'Quảng Ninh', 'Quảng Trị',
        'Sóc Trăng', 'Sơn La', 'Tây Ninh',
        'Thái Bình', 'Thái Nguyên', 'Thanh Hóa',
        'Thừa Thiên Huế', 'Tiền Giang', 'Trà Vinh',
        'Tuyên Quang', 'Vĩnh Long', 'Vĩnh Phúc',
        'Yên Bái', 'Phú Yên',
    );
    protected $text = "Nội dung khóa học
Khóa học Tiếng Anh giao tiếp ở giai đoạn cơ bản giúp học viên lấy lại nền tảng phát âm và ngữ pháp quan trọng, phù hợp cho người mất gốc muốn học lại từ đầu.";
    /**
     * Run the database seeders.
     *
     * @return void
     */
    public function run()
    {
        DB::table('user')->insert([
            'user_id' => 1,
            'password' => bcrypt('admin123'),
            'email' => 'admin',
            'full_name' => 'Manh Thuong',
            'phone_number' => '0853897558',
            'avatar' => 'thuongdz.jpg',
            'permission' => 0,
            'created_at' => rand(2020,2021).'/'.rand(1,12).'/'.rand(1,28),
        ]);
        for ($i = 2; $i < 50; $i++) {
            DB::table('user')->insert([
                'user_id' => $i,
                'password' => bcrypt('test'),
                'email' => 'test+' . $i . '@gmail.com',
                'full_name' => $this->firstName[array_rand($this->firstName)] . ' ' . $this->middleName[array_rand($this->middleName)] . ' ' . $this->lastName[array_rand($this->lastName)],
                'phone_number' => $this->phoneNumber[array_rand($this->phoneNumber)],
                'avatar' => 'avatar-clone.jpg',
                'status' => 1,
                'permission' => 1,
                'created_at' => rand(2020,2021).'/'.rand(1,12).'/'.rand(1,28),
            ]);
        }
        for ($i = 50; $i < 100; $i++) {
            DB::table('user')->insert([
                'user_id' => $i,
                'password' => bcrypt('test'),
                'email' => 'test+' . $i . '@gmail.com',
                'full_name' => $this->firstName[array_rand($this->firstName)] . ' ' . $this->middleName[array_rand($this->middleName)] . ' ' . $this->lastName[array_rand($this->lastName)],
                'phone_number' => $this->phoneNumber[array_rand($this->phoneNumber)],
                'avatar' => 'avatar-clone.jpg',
                'status' => 1,
                'permission' => 2,
                'created_at' => rand(2020,2021).'/'.rand(1,12).'/'.rand(1,28),
            ]);
        }
        $listCenter = $this->listCenter();
        for ($i = 50; $i < 100; $i++) {
            DB::table('english_center')->insert([
                'user_id' => $i,
                'name' => $listCenter[array_rand($listCenter)],
                'email' => 'center+' . $i . '@gmail.com',
                'address' => $this->address[array_rand($this->address)],
                'phone_number' => $this->phoneNumber[array_rand($this->phoneNumber)],
                'website' => 'test.com',
                'avatar' => 'center.jpg',
                'description' => $this->text,
                'area_id' => rand(1, 5),
                'ave_star' => rand(1, 5),
                'province_id' => rand(1, 63),
                'district_id' => rand(1, 709),
                'status' => 1,
                'created_at' => rand(2020,2021).'/'.rand(1,12).'/'.rand(1,28),
            ]);
        }
        $provinces = $this->getProvince();
        $districts = $this->getDistrict();
        foreach ($provinces as $province){
            DB::table('province')->insert([
                'id' => $province[0],
                'name' => $province[1],
            ]);
        }
        foreach ($districts as $district){
            DB::table('district')->insert([
                'id' => $district[0],
                'name' => $district[1],
                'prefix' => $district[2],
                'province_id' => $district[3],
            ]);
        }
        $listCourse = $this->listCourse();
        $listType = $this->listType();
        $listCustomer = $this->listCustomer();
        for ($i = 1; $i < 200; $i++) {
            DB::table('course')->insert([
                'course_id' => $i,
                'name' => $listCourse[array_rand($listCourse)],
                'center_id' => rand(1, 50),
                'price' => rand(1000000, 5000000),
                'discount' => rand(300000, 1000000),
                'type' => $listType[array_rand($listType)],
                'number_of_session' => rand(10, 20),
                'try_study' => rand(0, 1),
                'study_time' => '2021/04/10',
                'type_customer' => $listCustomer[array_rand($listCustomer)],
                'description' => $this->text,
                'input_requirement' => 'Không có',
                'out_requirement' => 'Không có',
                'input_point' => rand(0,450),
                'out_point' => rand(450,800),
                'status' => 1,
                'created_at' => rand(2020,2021).'/'.rand(1,12).'/'.rand(1,28),
            ]);
        }
    }
    public function listCourse()
    {
        return [
            "Tiếng Anh giao tiếp - Speak Out", "Speak Now", "Anh văn giao tiếp - Giai đoạn 1", "Giao tiếp căn bản", "Anh văn giao tiếp cơ bản", "English Communication", "Nền tảng A", "Giao tiếp quốc tế", "Tiếng Anh Giao Tiếp", "Tiếng Anh giao tiếp", "Basic - BS (Cho người mất gốc muốn sử dụng tiếng Anh giao tiếp cơ bản)", "Starter", "Tiếng Anh giao tiếp", "Anh văn nghe nói", "Giao tiếp 1", "Giao tiếp", "Tiếng Anh giao tiếp (OC)", "Tiếng Anh thiếu niên 50% người bản xứ", "Giao tiếp (Beginer, Sơ cấp A, Sơ cấp B)", "Anh văn Giao tiếp quốc tế", "Tiếng Anh giao tiếp", "Anh Văn Giao Tiếp", "Tiếng anh giao tiếp thông dụng", "(Ngoại trú) Giao tiếp - Beginner", "Level 1: Foundation - GVVN", "Giao tiếp (Dành cho HS-SV)", "Tiếng Anh giao tiếp - Beginner", "Tiếng Anh giao tiếp tổng quát", "RTC - Giao tiếp cơ bản", "FOUNDATION", "FRESHMAN (Pronounciation)", "Talk Plus", "Tiếng Anh Giao Tiếp", "Căn bản - Phát âm", "Standard Communication", "Tiếng Anh Giao Tiếp Quốc Tế", "Giao tiếp phỏng vấn", "VEnglish - Tiếng Anh giao tiếp", "Anh văn giao tiếp", "Giao tiếp tiếng Anh cơ bản", "Language Alive", "Tiếng Anh Giao tiếp", "tiếng Anh giao tiếp", "PE", "Speaking English", "Tiếng Anh giao tiếp", "1:1 với giáo viên bản ngữ", "Anh văn Giao Tiếp", "Tiếng Anh Giao tiếp", "Tiếng Anh giao tiếp sáng tạo (16+)", "Speaking Grammar 1", "Giao tiếp cơ bản (E-BASE)", "Phát âm chuẩn", "ANH VĂN GIAO TIẾP LEVEL 1", "Tiếng Anh thương mại", "Tiếng Anh giao tiếp", "Nói - Nghe Advanced 2", "Tiếng Anh giao tiếp", "Tiếng Anh giao tiếp", "Anh văn luyện nghe - nói", "Tiếng Anh căn bản", "Anh văn giao tiếp 100% giáo viên nước ngoài", "Tiếng Anh giao tiếp", "Gói học trải nghiệm giao tiếp", "General English", "Anh văn giao tiếp", "Starter", "Tiếng Anh giao tiếp", "Tiếng Anh giao tiếp", "Chương trình luyện nói tiếng Anh như người bản ngữ", "Căn bản", "Giao tiếp Quốc tế", "Luyện nói tiếng Anh như người bản ngữ", "Phát âm chuẩn", "Giao tiếp 1:1", "Tiếng Anh giao tiếp", "Giao tiếp & từ vựng ứng dụng căn bản", "Anh văn giao tiếp", "Anh văn Giao tiếp từ cơ bản đến văn phòng", "Anh văn giao tiếp", "Nghe – nói căn bản", "Anh Văn Giao Tiếp Cơ Bản Cho Người Yếu, Mất Gốc", "Tiếng Anh giao tiếp", "Giao tiếp cơ bản", "Tiếng Anh giao tiếp", "LUYỆN NGHE - NÓI 1, 2, 3, 4", "Anh văn giao tiếp Elementary", "Anh văn giao tiếp", "London Adults", "Anh văn giao tiếp cơ bản", "Giao tiếp cơ bản", "Tiếng Anh giao tiếp Conversation Basic", "Giao tiếp thực hành Beginners", "Giao tiếp căn bản", "Giao tiếp tiếng Anh luyện giọng Mỹ", "Tiếng Anh giao tiếp cơ bản", "Anh văn giao tiếp tổng quát", "Tiếng Anh giao tiếp", "Basic Communication", "Tiếng Anh giao tiếp", "Tiếng Anh giao tiếp", "Starters (Vỡ lòng)", "Nghe nói giao tiếp", "Basic", "Anh văn giao tiếp ứng dụng dành riêng cho người lớn ITALK", "Giao tiếp công việc", "Tiếng Anh giao tiếp", "Luyện phát âm chuẩn giọng Mỹ", "Anh văn giao tiếp", "English Rescue", "Giao tiếp lấy lại căn bản", "Giao tiếp cơ bản Foundation", "Giao tiếp căn bản (Basic English Communication)", "Tiếng Anh giao tiếp căn bản", "Giao tiếp Tiếng Anh", "Tiếng Anh giao tiếp", "Anh văn giao tiếp", "Tiếng Anh giao tiếp", "Tiếng Anh offline - Giao tiếp toàn diện", "Anh văn giao tiếp tổng quát", "Anh văn Giao tiếp Sơ cấp", "Nghe nói giao tiếp", "Free talk", "Pre-Speaking", "Giao tiếp - Thuyết trình", "Phát Âm Và Giao Tiếp Căn Bản", "Tiếng Anh giao tiếp cho người đi làm", "Anh văn Giao Tiếp Tổng quát (4 Kỹ năng)", "Interactive English", "Anh văn giao tiếp", "Tiếng Anh thực hành Nghe - Nói", "tiếng Anh giao tiếp"
        ];
    }

    public function listType()
    {
        return [
            'Giao tiếp cơ bản',
            'Giao tiếp nâng cao',
            'Giao tiếp trung cấp',
            'Giành cho trẻ em',
            'Business English'
        ];
    }

    public function listCustomer()
    {
        return [
            'Trẻ em',
            'Học sinh',
            'Người đi làm',
            'Mọi lứa tuổi'
        ];
    }
    public function listCenter()
    {
        return [
            0 => "Trung Tâm Tiếng Anh CES ",
            1 => "Nền tảng học tiếng Anh online 1-1 Kidtopi ",
            2 => "Trường Anh Ngữ Quốc Tế Clever Academy ",
            3 => "Trung Tâm Anh Ngữ Aroma - Tiếng Anh Cho Người Đi Làm ",
            4 => "Trung tâm Anh ngữ E4U ",
            5 => "Học Viện IvyPrep ",
            6 => "Trung tâm Anh ngữ Elingo IELTS ",
            7 => "Trung Tâm Anh Ngữ Cleverlearn ",
            8 => "Trung Tâm Luyện Thi Ielts Fighter ",
            9 => "Trung Tâm Language Link Vietnam ",
            10 => "Trung tâm anh ngữ ESOLD ",
            11 => "Trung Tâm Du Học Philippines PHILENGLISH ",
            12 => "Trung tâm Anh ngữ Sedu English ",
            13 => "Trung tâm AMATE English ",
            14 => "Học viện Đào tạo tiếng Anh và Kỹ năng Impactus ",
            15 => "Anh Ngữ Quốc Tế AMES ",
            16 => "Học viện Anh ngữ EQuest EQuest Academy ",
            17 => "Trung tâm Anh ngữ TES - Thầy Jimmy ",
            18 => "Tiếng Anh 123 ",
            19 => "Trung tâm Anh ngữ Jaxtina ",
            20 => "Trung Tâm Anh Ngữ Quốc Tế American Links ",
            21 => "Trung Tâm Anh Ngữ English Camp ",
            22 => "Trung Tâm Tiếng Anh CES ",
            23 => "Nền tảng học tiếng Anh online 1-1 Kidtopi ",
            24 => "Trung Tâm Du Học SET ",
            25 => "Trung Tâm Ngoại Ngữ Toeic Hà Nội ",
            26 => "Trung Tâm Tiếng Anh Anh Thầy ",
            27 => "Trung tâm TOEFL cô Giang ",
            28 => "Trung Tâm Anh Ngữ Apollo 360 ",
            29 => "Trung tâm Anh ngữ Headstart Vietnam ",
            30 => "Trung Tâm Ngoại Ngữ Multi Language ",
            31 => "Trung tâm du học và đào tạo ngoại ngữ Jelly Education ",
            32 => "Trung tâm học tiếng Anh online - Elight ",
            33 => "Trung Tâm Giáo Dục và Đào Tạo Pathways ",
            34 => "Trung Tâm Tiếng Anh NewLight ",
            35 => "Trung Tâm Anh Ngữ TAPL ",
            36 => "Trung Tâm Ngoại Ngữ Wider World ",
            37 => "Trung tâm tiếng anh English Beyond Education ",
            38 => "Trung Tâm Tiếng Anh GEEKO ",
            39 => "Trung Tâm Anh Ngữ Ms Phương ",
            40 => "Trung Tâm IELTS Cô Mai Lai ",
            41 => "Trung Tâm IELTS Cô Nhã ",
            42 => "Trung Tâm Anh Ngữ Bright Way ",
            43 => "Trung Tâm Tiếng Anh Nam Anh ",
            44 => "VietPhil Education Group ",
            45 => "Trung tâm Anh ngữ BST - Big Step Training ",
            46 => "Trung Tâm Anh Ngữ Mamita ",
            47 => "Trung Tâm Princeton English ",
            48 => "Trung tâm OSB STEAM English ",
            49 => "Trung tâm Anh ngữ Quốc tế D&C ",
            50 => "Trung tâm Anh ngữ Cambridge IEC ",
            51 => "Trung tâm Anh ngữ Learn4Life ",
            52 => "Trung tâm Nhật ngữ Nagomi ",
            53 => "Trung tâm Solar English ",
            54 => "Trung tâm Anh ngữ trẻ em Takus ",
            55 => "Trung tâm Anh ngữ New Era ",
            56 => "Trung tâm Anh ngữ Nuin Education ",
            57 => "Trung tâm Anh ngữ Linkee ",
            58 => "Trung tâm Anh ngữ Quốc tế Espeed ",
            59 => "Trung tâm Ngoại ngữ Phương Đông ",
            60 => "Trung tâm OSB STEAM English ",
            61 => "Trung tâm Anh ngữ Quốc tế D&C ",
            62 => "Trung tâm Anh ngữ Cambridge IEC ",
            63 => "Trung tâm Anh ngữ Learn4Life ",
            64 => "Trung tâm Nhật ngữ Nagomi ",
            65 => "Trung tâm Solar English ",
            66 => "Trung tâm Anh ngữ trẻ em Takus ",
            67 => "Trung tâm Anh ngữ New Era ",
            68 => "Trung tâm Anh ngữ Nuin Education ",
            69 => "Trung tâm Anh ngữ Linkee ",
            70 => "Trung tâm Anh ngữ Quốc tế Espeed ",
            71 => "Trung tâm Ngoại ngữ Phương Đông ",
            72 => "Trung Tâm English House ",
            73 => "Trung Tâm Tiếng Anh Elite ",
            74 => "Trung Tâm Anh Ngữ London ",
            75 => "Trung Tâm Học Tiếng Anh Trực Tuyến Homeclass ",
            76 => "Trung Tâm Dream House ",
            77 => "Trung tâm tiếng anh Tree ",
            78 => "Trung tâm tiếng Anh ATZ ",
            79 => "Trung tâm Talk Talk English ",
            80 => "Trung Tâm Anh Ngữ Bestway ",
            81 => "Trung Tâm Tiếng Anh H&H ",
            82 => "Trung Tâm Ngoại Ngữ Viet Advance ",
            83 => "Trung tâm tiếng Nhật Hikari ",
            84 => "Trung tâm Anh ngữ SLINK ",
            85 => "Trung tâm Anh ngữ Vicare ",
            86 => "Trung tâm Ngoại ngữ Up On ",
            87 => "Trung tâm Anh ngữ Quốc tế NEMO ",
            88 => "Trung tâm Anh ngữ Việt-Úc ",
            89 => "Trung tâm Anh ngữ Tâm Việt IQ ",
            90 => "Trung tâm ETS Việt Đức ",
            91 => "Trung tâm đào tạo Ngoại ngữ Benjamin ",
            92 => "Trung tâm Ngoại ngữ Moose ",
            93 => "Trung tâm Ngoại ngữ - Du học Việt Thắng ",
            94 => "Trung tâm Anh ngữ Kids' Dream ",
            95 => "Trung tâm Anh ngữ Big Star ",
            96 => "Trung Tâm Ngoại Ngữ Just Kids ",
            97 => "Trung Tâm Anh Ngữ Mika ",
            98 => "Trung Tâm May School ",
            99 => "Trung Tâm BenBen Foreign Language ",
            100 => "Trung Tâm RVi Hà Nội ",
            101 => "Trung Tâm IvyCation ",
            102 => "Popodoo Smart English ",
            103 => "Trung tâm Anh ngữ CLA ",
            104 => "Trung tâm kỹ năng anh ngữ Linkinworld ",
            105 => "Trung tâm anh ngữ L&D ",
            106 => "Trung tâm tiếng anh Roadmap ",
            107 => "Trung Tâm Tiếng Anh Grow Green ",
            108 => "Trung tâm tiếng Anh cô Hằng Bựa ",
            109 => "Trung Tâm Anh Ngữ Lê Nguyệt ",
            110 => "Học viện Giáo dục Quốc tế Elink Việt Nam ",
            111 => "Trung tâm Anh Ngữ Everest ",
            112 => "Trung Tâm Toeic Building ",
            113 => "Trung tâm anh ngữ UNIVER ",
            114 => "Trường ngoại ngữ Hà Nội ",
            115 => "Trung tâm tiếng Anh Hoangology ",
            116 => "Trung Tâm Anh Ngữ SmartLink ",
            117 => "Trung Tâm Anh Ngữ Joy School ",
            118 => "Trung Tâm Ngoại Ngữ Sunshine ",
            119 => "Trung Tâm Tiếng Anh ABBA ",
            120 => "Trường Ngoại ngữ Kiwi English ",
            121 => "Trung tâm Anh ngữ English Explorer ",
            122 => "Trung tâm tiếng Anh Loving English ",
            123 => "Trung tâm Ngoại ngữ Viettalent ",
            124 => "Trung tâm Anh ngữ Testlink ",
            125 => "Trung tâm Anh ngữ Quốc tế ECOLINK ",
            126 => "Trung tâm Ngoại ngữ Quốc tế Brainway ",
            127 => "Trung tâm Ngoại ngữ Quốc tế Diamond Star ",
            128 => "Trung tâm Go English ",
            129 => "Trung tâm tiếng Anh KiddyLand ",
            130 => "Trung tâm Anh ngữ Tin học Sydney ",
            131 => "Trung tâm Gitizen English ",
            132 => "Trường Anh Ngữ Quốc Tế APEC ",
            133 => "Trung Tâm Anh Ngữ Quốc Tế Shelton ",
            134 => "Trung Tâm Tiếng Anh Edumax ",
            135 => "Trung Tâm Ngoại Ngữ Hà Nội ",
            136 => "Trung Tâm Thầy Quý Tuấn TOEIC 990/990 ",
            137 => "Trung tâm IELTS Linh UK ",
            138 => "Trung Tâm Tiếng Anh 5epro ",
            139 => "Anh Ngữ Quốc Tế Educare ",
            140 => "Trung tâm ngoại ngữ Gee ",
            141 => "Trung Tâm Ngoại Ngữ Tiếng Anh LiLy ",
            142 => "Trung Tâm Anh Ngữ iSpeaking ",
            143 => "Hệ Thống Anh Ngữ Trẻ Em Vietchild ",
            144 => "Học viện Anh ngữ Clever Clogs ",
            145 => "Trung tâm Du học - Ngoại ngữ ITM ",
            146 => "Trung tâm Ngoại ngữ tin học E.Future ",
            147 => "Trung tâm đào tạo nhân lực PTM ",
            148 => "Trung tâm Tiếng Anh Western Ocean ",
            149 => "Trung tâm Anh ngữ ITD ",
            150 => "Trung tâm Anh ngữ Capitole ",
            151 => "Trung tâm Ngoại ngữ Eduline ",
            152 => "Trung tâm Ngoại ngữ Quốc tế HACIC ",
            153 => "Trung tâm Anh ngữ Sunkids",
        ];
    }
    public function getProvince(){
        return [
            [1, 'Hồ Chí Minh', 'SG'],
            [2, 'Hà Nội', 'HN'],
            [3, 'Đà Nẵng', 'DDN'],
            [4, 'Bình Dương', 'BD'],
            [5, 'Đồng Nai', 'DNA'],
            [6, 'Khánh Hòa', 'KH'],
            [7, 'Hải Phòng', 'HP'],
            [8, 'Long An', 'LA'],
            [9, 'Quảng Nam', 'QNA'],
            [10, 'Bà Rịa Vũng Tàu', 'VT'],
            [11, 'Đắk Lắk', 'DDL'],
            [12, 'Cần Thơ', 'CT'],
            [13, 'Bình Thuận  ', 'BTH'],
            [14, 'Lâm Đồng', 'LDD'],
            [15, 'Thừa Thiên Huế', 'TTH'],
            [16, 'Kiên Giang', 'KG'],
            [17, 'Bắc Ninh', 'BN'],
            [18, 'Quảng Ninh', 'QNI'],
            [19, 'Thanh Hóa', 'TH'],
            [20, 'Nghệ An', 'NA'],
            [21, 'Hải Dương', 'HD'],
            [22, 'Gia Lai', 'GL'],
            [23, 'Bình Phước', 'BP'],
            [24, 'Hưng Yên', 'HY'],
            [25, 'Bình Định', 'BDD'],
            [26, 'Tiền Giang', 'TG'],
            [27, 'Thái Bình', 'TB'],
            [28, 'Bắc Giang', 'BG'],
            [29, 'Hòa Bình', 'HB'],
            [30, 'An Giang', 'AG'],
            [31, 'Vĩnh Phúc', 'VP'],
            [32, 'Tây Ninh', 'TNI'],
            [33, 'Thái Nguyên', 'TN'],
            [34, 'Lào Cai', 'LCA'],
            [35, 'Nam Định', 'NDD'],
            [36, 'Quảng Ngãi', 'QNG'],
            [37, 'Bến Tre', 'BTR'],
            [38, 'Đắk Nông', 'DNO'],
            [39, 'Cà Mau', 'CM'],
            [40, 'Vĩnh Long', 'VL'],
            [41, 'Ninh Bình', 'NB'],
            [42, 'Phú Thọ', 'PT'],
            [43, 'Ninh Thuận', 'NT'],
            [44, 'Phú Yên', 'PY'],
            [45, 'Hà Nam', 'HNA'],
            [46, 'Hà Tĩnh', 'HT'],
            [47, 'Đồng Tháp', 'DDT'],
            [48, 'Sóc Trăng', 'ST'],
            [49, 'Kon Tum', 'KT'],
            [50, 'Quảng Bình', 'QB'],
            [51, 'Quảng Trị', 'QT'],
            [52, 'Trà Vinh', 'TV'],
            [53, 'Hậu Giang', 'HGI'],
            [54, 'Sơn La', 'SL'],
            [55, 'Bạc Liêu', 'BL'],
            [56, 'Yên Bái', 'YB'],
            [57, 'Tuyên Quang', 'TQ'],
            [58, 'Điện Biên', 'DDB'],
            [59, 'Lai Châu', 'LCH'],
            [60, 'Lạng Sơn', 'LS'],
            [61, 'Hà Giang', 'HG'],
            [62, 'Bắc Kạn', 'BK'],
            [63, 'Cao Bằng', 'CB']
        ];
    }
    public function getDistrict(){
        return [
            [1, 'Bình Chánh', 'Huyện', 1],
            [2, 'Bình Tân', 'Quận', 1],
            [3, 'Bình Thạnh', 'Quận', 1],
            [4, 'Cần Giờ', 'Huyện', 1],
            [5, 'Củ Chi', 'Huyện', 1],
            [6, 'Gò Vấp', 'Quận', 1],
            [7, 'Hóc Môn', 'Huyện', 1],
            [8, 'Nhà Bè', 'Huyện', 1],
            [9, 'Phú Nhuận', 'Quận', 1],
            [10, 'Quận 1', '', 1],
            [11, 'Quận 10', '', 1],
            [12, 'Quận 11', '', 1],
            [13, 'Quận 12', '', 1],
            [14, 'Quận 2', '', 1],
            [15, 'Quận 3', '', 1],
            [16, 'Quận 4', '', 1],
            [17, 'Quận 5', '', 1],
            [18, 'Quận 6', '', 1],
            [19, 'Quận 7', '', 1],
            [20, 'Quận 8', '', 1],
            [21, 'Quận 9', '', 1],
            [22, 'Tân Bình', 'Quận', 1],
            [23, 'Tân Phú', 'Quận', 1],
            [24, 'Thủ Đức', 'Quận', 1],
            [25, 'Ba Đình', 'Quận', 2],
            [26, 'Ba Vì', 'Huyện', 2],
            [27, 'Bắc Từ Liêm', 'Quận', 2],
            [28, 'Cầu Giấy', 'Quận', 2],
            [29, 'Chương Mỹ', 'Huyện', 2],
            [30, 'Đan Phượng', 'Huyện', 2],
            [31, 'Đông Anh', 'Huyện', 2],
            [32, 'Đống Đa', 'Quận', 2],
            [33, 'Gia Lâm', 'Huyện', 2],
            [34, 'Hà Đông', 'Quận', 2],
            [35, 'Hai Bà Trưng', 'Quận', 2],
            [36, 'Hoài Đức', 'Huyện', 2],
            [37, 'Hoàn Kiếm', 'Quận', 2],
            [38, 'Hoàng Mai', 'Quận', 2],
            [39, 'Long Biên', 'Quận', 2],
            [40, 'Mê Linh', 'Huyện', 2],
            [41, 'Mỹ Đức', 'Huyện', 2],
            [42, 'Nam Từ Liêm', 'Quận', 2],
            [43, 'Phú Xuyên', 'Huyện', 2],
            [44, 'Phúc Thọ', 'Huyện', 2],
            [45, 'Quốc Oai', 'Huyện', 2],
            [46, 'Sóc Sơn', 'Huyện', 2],
            [47, 'Sơn Tây', 'Thị xã', 2],
            [48, 'Tây Hồ', 'Quận', 2],
            [49, 'Thạch Thất', 'Huyện', 2],
            [50, 'Thanh Oai', 'Huyện', 2],
            [51, 'Thanh Trì', 'Huyện', 2],
            [52, 'Thanh Xuân', 'Quận', 2],
            [53, 'Thường Tín', 'Huyện', 2],
            [54, 'Ứng Hòa', 'Huyện', 2],
            [55, 'Cẩm Lệ', 'Quận', 3],
            [56, 'Hải Châu', 'Quận', 3],
            [57, 'Hòa Vang', 'Huyện', 3],
            [58, 'Hoàng Sa', 'Huyện', 3],
            [59, 'Liên Chiểu', 'Quận', 3],
            [60, 'Ngũ Hành Sơn', 'Quận', 3],
            [61, 'Sơn Trà', 'Quận', 3],
            [62, 'Thanh Khê', 'Quận', 3],
            [63, 'Bàu Bàng', 'Huyện', 4],
            [64, 'Bến Cát', 'Thị xã', 4],
            [65, 'Dầu Tiếng', 'Huyện', 4],
            [66, 'Dĩ An', 'Thị xã', 4],
            [67, 'Phú Giáo', 'Huyện', 4],
            [68, 'Tân Uyên', 'Huyện', 4],
            [69, 'Thủ Dầu Một', 'Thị xã', 4],
            [70, 'Thuận An', 'Huyện', 4],
            [71, 'Biên Hòa', 'Thành phố', 5],
            [72, 'Cẩm Mỹ', 'Huyện', 5],
            [73, 'Định Quán', 'Huyện', 5],
            [74, 'Long Khánh', 'Thị xã', 5],
            [75, 'Long Thành', 'Huyện', 5],
            [76, 'Nhơn Trạch', 'Huyện', 5],
            [77, 'Tân Phú', 'Quận', 5],
            [78, 'Thống Nhất', 'Huyện', 5],
            [79, 'Trảng Bom', 'Huyện', 5],
            [80, 'Vĩnh Cửu', 'Huyện', 5],
            [81, 'Xuân Lộc', 'Huyện', 5],
            [82, 'Cam Lâm', 'Huyện', 6],
            [83, 'Cam Ranh', 'Thành phố', 6],
            [84, 'Diên Khánh', 'Huyện', 6],
            [85, 'Khánh Sơn', 'Huyện', 6],
            [86, 'Khánh Vĩnh', 'Huyện', 6],
            [87, 'Nha Trang', 'Thành phố', 6],
            [88, 'Ninh Hòa', 'Thị xã', 6],
            [89, 'Trường Sa', 'Huyện', 6],
            [90, 'Vạn Ninh', 'Huyện', 6],
            [91, 'An Dương', 'Huyện', 7],
            [92, 'An Lão', 'Huyện', 7],
            [93, 'Bạch Long Vĩ', 'Huyện', 7],
            [94, 'Cát Hải', 'Huyện', 7],
            [95, 'Đồ Sơn', 'Quận', 7],
            [96, 'Dương Kinh', 'Quận', 7],
            [97, 'Hải An', 'Quận', 7],
            [98, 'Hồng Bàng', 'Quận', 7],
            [99, 'Kiến An', 'Quận', 7],
            [100, 'Kiến Thụy', 'Huyện', 7],
            [101, 'Lê Chân', 'Quận', 7],
            [102, 'Ngô Quyền', 'Quận', 7],
            [103, 'Thủy Nguyên', 'Huyện', 7],
            [104, 'Tiên Lãng', 'Huyện', 7],
            [105, 'Vĩnh Bảo', 'Huyện', 7],
            [106, 'Bến Lức', 'Huyện', 8],
            [107, 'Cần Đước', 'Huyện', 8],
            [108, 'Cần Giuộc', 'Huyện', 8],
            [109, 'Châu Thành', 'Huyện', 8],
            [110, 'Đức Hòa', 'Huyện', 8],
            [111, 'Đức Huệ', 'Huyện', 8],
            [112, 'Kiến Tường', 'Thị xã', 8],
            [113, 'Mộc Hóa', 'Huyện', 8],
            [114, 'Tân An', 'Thành phố', 8],
            [115, 'Tân Hưng', 'Huyện', 8],
            [116, 'Tân Thạnh', 'Huyện', 8],
            [117, 'Tân Trụ', 'Huyện', 8],
            [118, 'Thạnh Hóa', 'Huyện', 8],
            [119, 'Thủ Thừa', 'Huyện', 8],
            [120, 'Vĩnh Hưng', 'Huyện', 8],
            [121, 'Bắc Trà My', 'Huyện', 9],
            [122, 'Đại Lộc', 'Huyện', 9],
            [123, 'Điện Bàn', 'Huyện', 9],
            [124, 'Đông Giang', 'Huyện', 9],
            [125, 'Duy Xuyên', 'Huyện', 9],
            [126, 'Hiệp Đức', 'Huyện', 9],
            [127, 'Hội An', 'Thành phố', 9],
            [128, 'Nam Giang', 'Huyện', 9],
            [129, 'Nam Trà My', 'Huyện', 9],
            [130, 'Nông Sơn', 'Huyện', 9],
            [131, 'Núi Thành', 'Huyện', 9],
            [132, 'Phú Ninh', 'Huyện', 9],
            [133, 'Phước Sơn', 'Huyện', 9],
            [134, 'Quế Sơn', 'Huyện', 9],
            [135, 'Tam Kỳ', 'Thành phố', 9],
            [136, 'Tây Giang', 'Huyện', 9],
            [137, 'Thăng Bình', 'Huyện', 9],
            [138, 'Tiên Phước', 'Huyện', 9],
            [139, 'Bà Rịa', 'Thị xã', 10],
            [140, 'Châu Đức', 'Huyện', 10],
            [141, 'Côn Đảo', 'Huyện', 10],
            [142, 'Đất Đỏ', 'Huyện', 10],
            [143, 'Long Điền', 'Huyện', 10],
            [144, 'Tân Thành', 'Huyện', 10],
            [145, 'Vũng Tàu', 'Thành phố', 10],
            [146, 'Xuyên Mộc', 'Huyện', 10],
            [147, 'Buôn Đôn', 'Huyện', 11],
            [148, 'Buôn Hồ', 'Thị xã', 11],
            [149, 'Buôn Ma Thuột', 'Thành phố', 11],
            [150, 'Cư Kuin', 'Huyện', 11],
            [151, 'Cư M\'gar', 'Huyện', 11],
            [152, 'Ea H\'Leo', 'Huyện', 11],
            [153, 'Ea Kar', 'Huyện', 11],
            [154, 'Ea Súp', 'Huyện', 11],
            [155, 'Krông Ana', 'Huyện', 11],
            [156, 'Krông Bông', 'Huyện', 11],
            [157, 'Krông Buk', 'Huyện', 11],
            [158, 'Krông Năng', 'Huyện', 11],
            [159, 'Krông Pắc', 'Huyện', 11],
            [160, 'Lăk', 'Huyện', 11],
            [161, 'M\'Đrăk', 'Huyện', 11],
            [162, ' Thới Lai', 'Huyện', 12],
            [163, 'Bình Thủy', 'Quận', 12],
            [164, 'Cái Răng', 'Quận', 12],
            [165, 'Cờ Đỏ', 'Huyện', 12],
            [166, 'Ninh Kiều', 'Quận', 12],
            [167, 'Ô Môn', 'Quận', 12],
            [168, 'Phong Điền', 'Huyện', 12],
            [169, 'Thốt Nốt', 'Quận', 12],
            [170, 'Vĩnh Thạnh', 'Huyện', 12],
            [171, 'Bắc Bình', 'Huyện', 13],
            [172, 'Đảo Phú Quý', 'Huyện', 13],
            [173, 'Đức Linh', 'Huyện', 13],
            [174, 'Hàm Tân', 'Huyện', 13],
            [175, 'Hàm Thuận Bắc', 'Huyện', 13],
            [176, 'Hàm Thuận Nam', 'Huyện', 13],
            [177, 'La Gi', 'Thị xã', 13],
            [178, 'Phan Thiết', 'Thành phố', 13],
            [179, 'Tánh Linh', 'Huyện', 13],
            [180, 'Tuy Phong', 'Huyện', 13],
            [181, 'Bảo Lâm', 'Huyện', 14],
            [182, 'Bảo Lộc', 'Thành phố', 14],
            [183, 'Cát Tiên', 'Huyện', 14],
            [184, 'Đạ Huoai', 'Huyện', 14],
            [185, 'Đà Lạt', 'Thành phố', 14],
            [186, 'Đạ Tẻh', 'Huyện', 14],
            [187, 'Đam Rông', 'Huyện', 14],
            [188, 'Di Linh', 'Huyện', 14],
            [189, 'Đơn Dương', 'Huyện', 14],
            [190, 'Đức Trọng', 'Huyện', 14],
            [191, 'Lạc Dương', 'Huyện', 14],
            [192, 'Lâm Hà', 'Huyện', 14],
            [193, 'A Lưới', 'Huyện', 15],
            [194, 'Huế', 'Thành phố', 15],
            [195, 'Hương Thủy', 'Thị xã', 15],
            [196, 'Hương Trà', 'Huyện', 15],
            [197, 'Nam Đông', 'Huyện', 15],
            [198, 'Phong Điền', 'Huyện', 15],
            [199, 'Phú Lộc', 'Huyện', 15],
            [200, 'Phú Vang', 'Huyện', 15],
            [201, 'Quảng Điền', 'Huyện', 15],
            [202, 'An Biên', 'Huyện', 16],
            [203, 'An Minh', 'Huyện', 16],
            [204, 'Châu Thành', 'Huyện', 16],
            [205, 'Giang Thành', 'Huyện', 16],
            [206, 'Giồng Riềng', 'Huyện', 16],
            [207, 'Gò Quao', 'Huyện', 16],
            [208, 'Hà Tiên', 'Thị xã', 16],
            [209, 'Hòn Đất', 'Huyện', 16],
            [210, 'Kiên Hải', 'Huyện', 16],
            [211, 'Kiên Lương', 'Huyện', 16],
            [212, 'Phú Quốc', 'Huyện', 16],
            [213, 'Rạch Giá', 'Thành phố', 16],
            [214, 'Tân Hiệp', 'Huyện', 16],
            [215, 'U minh Thượng', 'Huyện', 16],
            [216, 'Vĩnh Thuận', 'Huyện', 16],
            [217, 'Bắc Ninh', 'Thành phố', 17],
            [218, 'Gia Bình', 'Huyện', 17],
            [219, 'Lương Tài', 'Huyện', 17],
            [220, 'Quế Võ', 'Huyện', 17],
            [221, 'Thuận Thành', 'Huyện', 17],
            [222, 'Tiên Du', 'Huyện', 17],
            [223, 'Từ Sơn', 'Thị xã', 17],
            [224, 'Yên Phong', 'Huyện', 17],
            [225, 'Ba Chẽ', 'Huyện', 18],
            [226, 'Bình Liêu', 'Huyện', 18],
            [227, 'Cẩm Phả', 'Thành phố', 18],
            [228, 'Cô Tô', 'Huyện', 18],
            [229, 'Đầm Hà', 'Huyện', 18],
            [230, 'Đông Triều', 'Huyện', 18],
            [231, 'Hạ Long', 'Thành phố', 18],
            [232, 'Hải Hà', 'Huyện', 18],
            [233, 'Hoành Bồ', 'Huyện', 18],
            [234, 'Móng Cái', 'Thành phố', 18],
            [235, 'Quảng Yên', 'Huyện', 18],
            [236, 'Tiên Yên', 'Huyện', 18],
            [237, 'Uông Bí', 'Thị xã', 18],
            [238, 'Vân Đồn', 'Huyện', 18],
            [239, 'Bá Thước', 'Huyện', 19],
            [240, 'Bỉm Sơn', 'Thị xã', 19],
            [241, 'Cẩm Thủy', 'Huyện', 19],
            [242, 'Đông Sơn', 'Huyện', 19],
            [243, 'Hà Trung', 'Huyện', 19],
            [244, 'Hậu Lộc', 'Huyện', 19],
            [245, 'Hoằng Hóa', 'Huyện', 19],
            [246, 'Lang Chánh', 'Huyện', 19],
            [247, 'Mường Lát', 'Huyện', 19],
            [248, 'Nga Sơn', 'Huyện', 19],
            [249, 'Ngọc Lặc', 'Huyện', 19],
            [250, 'Như Thanh', 'Huyện', 19],
            [251, 'Như Xuân', 'Huyện', 19],
            [252, 'Nông Cống', 'Huyện', 19],
            [253, 'Quan Hóa', 'Huyện', 19],
            [254, 'Quan Sơn', 'Huyện', 19],
            [255, 'Quảng Xương', 'Huyện', 19],
            [256, 'Sầm Sơn', 'Thị xã', 19],
            [257, 'Thạch Thành', 'Huyện', 19],
            [258, 'Thanh Hóa', 'Thành phố', 19],
            [259, 'Thiệu Hóa', 'Huyện', 19],
            [260, 'Thọ Xuân', 'Huyện', 19],
            [261, 'Thường Xuân', 'Huyện', 19],
            [262, 'Tĩnh Gia', 'Huyện', 19],
            [263, 'Triệu Sơn', 'Huyện', 19],
            [264, 'Vĩnh Lộc', 'Huyện', 19],
            [265, 'Yên Định', 'Huyện', 19],
            [266, 'Anh Sơn', 'Huyện', 20],
            [267, 'Con Cuông', 'Huyện', 20],
            [268, 'Cửa Lò', 'Thị xã', 20],
            [269, 'Diễn Châu', 'Huyện', 20],
            [270, 'Đô Lương', 'Huyện', 20],
            [271, 'Hoàng Mai', 'Thị xã', 20],
            [272, 'Hưng Nguyên', 'Huyện', 20],
            [273, 'Kỳ Sơn', 'Huyện', 20],
            [274, 'Nam Đàn', 'Huyện', 20],
            [275, 'Nghi Lộc', 'Huyện', 20],
            [276, 'Nghĩa Đàn', 'Huyện', 20],
            [277, 'Quế Phong', 'Huyện', 20],
            [278, 'Quỳ Châu', 'Huyện', 20],
            [279, 'Quỳ Hợp', 'Huyện', 20],
            [280, 'Quỳnh Lưu', 'Huyện', 20],
            [281, 'Tân Kỳ', 'Huyện', 20],
            [282, 'Thái Hòa', 'Thị xã', 20],
            [283, 'Thanh Chương', 'Huyện', 20],
            [284, 'Tương Dương', 'Huyện', 20],
            [285, 'Vinh', 'Thành phố', 20],
            [286, 'Yên Thành', 'Huyện', 20],
            [287, 'Bình Giang', 'Huyện', 21],
            [288, 'Cẩm Giàng', 'Huyện', 21],
            [289, 'Chí Linh', 'Thị xã', 21],
            [290, 'Gia Lộc', 'Huyện', 21],
            [291, 'Hải Dương', 'Thành phố', 21],
            [292, 'Kim Thành', 'Huyện', 21],
            [293, 'Kinh Môn', 'Huyện', 21],
            [294, 'Nam Sách', 'Huyện', 21],
            [295, 'Ninh Giang', 'Huyện', 21],
            [296, 'Thanh Hà', 'Huyện', 21],
            [297, 'Thanh Miện', 'Huyện', 21],
            [298, 'Tứ Kỳ', 'Huyện', 21],
            [299, 'An Khê', 'Thị xã', 22],
            [300, 'AYun Pa', 'Thị xã', 22],
            [301, 'Chư Păh', 'Huyện', 22],
            [302, 'Chư Pưh', 'Huyện', 22],
            [303, 'Chư Sê', 'Huyện', 22],
            [304, 'ChưPRông', 'Huyện', 22],
            [305, 'Đăk Đoa', 'Huyện', 22],
            [306, 'Đăk Pơ', 'Huyện', 22],
            [307, 'Đức Cơ', 'Huyện', 22],
            [308, 'Ia Grai', 'Huyện', 22],
            [309, 'Ia Pa', 'Huyện', 22],
            [310, 'KBang', 'Huyện', 22],
            [311, 'Kông Chro', 'Huyện', 22],
            [312, 'Krông Pa', 'Huyện', 22],
            [313, 'Mang Yang', 'Huyện', 22],
            [314, 'Phú Thiện', 'Huyện', 22],
            [315, 'Plei Ku', 'Thành phố', 22],
            [316, 'Bình Long', 'Thị xã', 23],
            [317, 'Bù Đăng', 'Huyện', 23],
            [318, 'Bù Đốp', 'Huyện', 23],
            [319, 'Bù Gia Mập', 'Huyện', 23],
            [320, 'Chơn Thành', 'Huyện', 23],
            [321, 'Đồng Phú', 'Huyện', 23],
            [322, 'Đồng Xoài', 'Thị xã', 23],
            [323, 'Hớn Quản', 'Huyện', 23],
            [324, 'Lộc Ninh', 'Huyện', 23],
            [325, 'Phú Riềng', 'Huyện', 23],
            [326, 'Phước Long', 'Thị xã', 23],
            [327, 'Ân Thi', 'Huyện', 24],
            [328, 'Hưng Yên', 'Thành phố', 24],
            [329, 'Khoái Châu', 'Huyện', 24],
            [330, 'Kim Động', 'Huyện', 24],
            [331, 'Mỹ Hào', 'Huyện', 24],
            [332, 'Phù Cừ', 'Huyện', 24],
            [333, 'Tiên Lữ', 'Huyện', 24],
            [334, 'Văn Giang', 'Huyện', 24],
            [335, 'Văn Lâm', 'Huyện', 24],
            [336, 'Yên Mỹ', 'Huyện', 24],
            [337, 'An Lão', 'Huyện', 25],
            [338, 'An Nhơn', 'Huyện', 25],
            [339, 'Hoài Ân', 'Huyện', 25],
            [340, 'Hoài Nhơn', 'Huyện', 25],
            [341, 'Phù Cát', 'Huyện', 25],
            [342, 'Phù Mỹ', 'Huyện', 25],
            [343, 'Quy Nhơn', 'Thành phố', 25],
            [344, 'Tây Sơn', 'Huyện', 25],
            [345, 'Tuy Phước', 'Huyện', 25],
            [346, 'Vân Canh', 'Huyện', 25],
            [347, 'Vĩnh Thạnh', 'Huyện', 25],
            [348, 'Cái Bè', 'Huyện', 26],
            [349, 'Cai Lậy', 'Thị xã', 26],
            [350, 'Châu Thành', 'Huyện', 26],
            [351, 'Chợ Gạo', 'Huyện', 26],
            [352, 'Gò Công', 'Thị xã', 26],
            [353, 'Gò Công Đông', 'Huyện', 26],
            [354, 'Gò Công Tây', 'Huyện', 26],
            [355, 'Huyện Cai Lậy', 'Huyện', 26],
            [356, 'Mỹ Tho', 'Thành phố', 26],
            [357, 'Tân Phú Đông', 'Huyện', 26],
            [358, 'Tân Phước', 'Huyện', 26],
            [359, 'Đông Hưng', 'Huyện', 27],
            [360, 'Hưng Hà', 'Huyện', 27],
            [361, 'Kiến Xương', 'Huyện', 27],
            [362, 'Quỳnh Phụ', 'Huyện', 27],
            [363, 'Thái Bình', 'Thành phố', 27],
            [364, 'Thái Thuỵ', 'Huyện', 27],
            [365, 'Tiền Hải', 'Huyện', 27],
            [366, 'Vũ Thư', 'Huyện', 27],
            [367, 'Bắc Giang', 'Thành phố', 28],
            [368, 'Hiệp Hòa', 'Huyện', 28],
            [369, 'Lạng Giang', 'Huyện', 28],
            [370, 'Lục Nam', 'Huyện', 28],
            [371, 'Lục Ngạn', 'Huyện', 28],
            [372, 'Sơn Động', 'Huyện', 28],
            [373, 'Tân Yên', 'Huyện', 28],
            [374, 'Việt Yên', 'Huyện', 28],
            [375, 'Yên Dũng', 'Huyện', 28],
            [376, 'Yên Thế', 'Huyện', 28],
            [377, 'Cao Phong', 'Huyện', 29],
            [378, 'Đà Bắc', 'Huyện', 29],
            [379, 'Hòa Bình', 'Thành phố', 29],
            [380, 'Kim Bôi', 'Huyện', 29],
            [381, 'Kỳ Sơn', 'Huyện', 29],
            [382, 'Lạc Sơn', 'Huyện', 29],
            [383, 'Lạc Thủy', 'Huyện', 29],
            [384, 'Lương Sơn', 'Huyện', 29],
            [385, 'Mai Châu', 'Huyện', 29],
            [386, 'Tân Lạc', 'Huyện', 29],
            [387, 'Yên Thủy', 'Huyện', 29],
            [388, 'An Phú', 'Huyện', 30],
            [389, 'Châu Đốc', 'Thị xã', 30],
            [390, 'Châu Phú', 'Huyện', 30],
            [391, 'Châu Thành', 'Huyện', 30],
            [392, 'Chợ Mới', 'Huyện', 30],
            [393, 'Long Xuyên', 'Thành phố', 30],
            [394, 'Phú Tân', 'Huyện', 30],
            [395, 'Tân Châu', 'Thị xã', 30],
            [396, 'Thoại Sơn', 'Huyện', 30],
            [397, 'Tịnh Biên', 'Huyện', 30],
            [398, 'Tri Tôn', 'Huyện', 30],
            [399, 'Bình Xuyên', 'Huyện', 31],
            [400, 'Lập Thạch', 'Huyện', 31],
            [401, 'Phúc Yên', 'Thị xã', 31],
            [402, 'Sông Lô', 'Huyện', 31],
            [403, 'Tam Đảo', 'Huyện', 31],
            [404, 'Tam Dương', 'Huyện', 31],
            [405, 'Vĩnh Tường', 'Huyện', 31],
            [406, 'Vĩnh Yên', 'Thành phố', 31],
            [407, 'Yên Lạc', 'Huyện', 31],
            [408, 'Bến Cầu', 'Huyện', 32],
            [409, 'Châu Thành', 'Huyện', 32],
            [410, 'Dương Minh Châu', 'Huyện', 32],
            [411, 'Gò Dầu', 'Huyện', 32],
            [412, 'Hòa Thành', 'Huyện', 32],
            [413, 'Tân Biên', 'Huyện', 32],
            [414, 'Tân Châu', 'Huyện', 32],
            [415, 'Tây Ninh', 'Thị xã', 32],
            [416, 'Trảng Bàng', 'Huyện', 32],
            [417, 'Đại Từ', 'Huyện', 33],
            [418, 'Định Hóa', 'Huyện', 33],
            [419, 'Đồng Hỷ', 'Huyện', 33],
            [420, 'Phổ Yên', 'Huyện', 33],
            [421, 'Phú Bình', 'Huyện', 33],
            [422, 'Phú Lương', 'Huyện', 33],
            [423, 'Sông Công', 'Thị xã', 33],
            [424, 'Thái Nguyên', 'Thành phố', 33],
            [425, 'Võ Nhai', 'Huyện', 33],
            [426, 'Bắc Hà', 'Huyện', 34],
            [427, 'Bảo Thắng', 'Huyện', 34],
            [428, 'Bảo Yên', 'Huyện', 34],
            [429, 'Bát Xát', 'Huyện', 34],
            [430, 'Lào Cai', 'Thành phố', 34],
            [431, 'Mường Khương', 'Huyện', 34],
            [432, 'Sa Pa', 'Huyện', 34],
            [433, 'Văn Bàn', 'Huyện', 34],
            [434, 'Xi Ma Cai', 'Huyện', 34],
            [435, 'Giao Thủy', 'Huyện', 35],
            [436, 'Hải Hậu', 'Huyện', 35],
            [437, 'Mỹ Lộc', 'Huyện', 35],
            [438, 'Nam Định', 'Thành phố', 35],
            [439, 'Nam Trực', 'Huyện', 35],
            [440, 'Nghĩa Hưng', 'Huyện', 35],
            [441, 'Trực Ninh', 'Huyện', 35],
            [442, 'Vụ Bản', 'Huyện', 35],
            [443, 'Xuân Trường', 'Huyện', 35],
            [444, 'Ý Yên', 'Huyện', 35],
            [445, 'Ba Tơ', 'Huyện', 36],
            [446, 'Bình Sơn', 'Huyện', 36],
            [447, 'Đức Phổ', 'Huyện', 36],
            [448, 'Lý Sơn', 'Huyện', 36],
            [449, 'Minh Long', 'Huyện', 36],
            [450, 'Mộ Đức', 'Huyện', 36],
            [451, 'Nghĩa Hành', 'Huyện', 36],
            [452, 'Quảng Ngãi', 'Thành phố', 36],
            [453, 'Sơn Hà', 'Huyện', 36],
            [454, 'Sơn Tây', 'Huyện', 36],
            [455, 'Sơn Tịnh', 'Huyện', 36],
            [456, 'Tây Trà', 'Huyện', 36],
            [457, 'Trà Bồng', 'Huyện', 36],
            [458, 'Tư Nghĩa', 'Huyện', 36],
            [459, 'Ba Tri', 'Huyện', 37],
            [460, 'Bến Tre', 'Thành phố', 37],
            [461, 'Bình Đại', 'Huyện', 37],
            [462, 'Châu Thành', 'Huyện', 37],
            [463, 'Chợ Lách', 'Huyện', 37],
            [464, 'Giồng Trôm', 'Huyện', 37],
            [465, 'Mỏ Cày Bắc', 'Huyện', 37],
            [466, 'Mỏ Cày Nam', 'Huyện', 37],
            [467, 'Thạnh Phú', 'Huyện', 37],
            [468, 'Cư Jút', 'Huyện', 38],
            [469, 'Dăk GLong', 'Huyện', 38],
            [470, 'Dăk Mil', 'Huyện', 38],
            [471, 'Dăk R\'Lấp', 'Huyện', 38],
            [472, 'Dăk Song', 'Huyện', 38],
            [473, 'Gia Nghĩa', 'Thị xã', 38],
            [474, 'Krông Nô', 'Huyện', 38],
            [475, 'Tuy Đức', 'Huyện', 38],
            [476, 'Cà Mau', 'Thành phố', 39],
            [477, 'Cái Nước', 'Huyện', 39],
            [478, 'Đầm Dơi', 'Huyện', 39],
            [479, 'Năm Căn', 'Huyện', 39],
            [480, 'Ngọc Hiển', 'Huyện', 39],
            [481, 'Phú Tân', 'Huyện', 39],
            [482, 'Thới Bình', 'Huyện', 39],
            [483, 'Trần Văn Thời', 'Huyện', 39],
            [484, 'U Minh', 'Huyện', 39],
            [485, 'Bình Minh', 'Huyện', 40],
            [486, 'Bình Tân', 'Quận', 40],
            [487, 'Long Hồ', 'Huyện', 40],
            [488, 'Mang Thít', 'Huyện', 40],
            [489, 'Tam Bình', 'Huyện', 40],
            [490, 'Trà Ôn', 'Huyện', 40],
            [491, 'Vĩnh Long', 'Thành phố', 40],
            [492, 'Vũng Liêm', 'Huyện', 40],
            [493, 'Gia Viễn', 'Huyện', 41],
            [494, 'Hoa Lư', 'Huyện', 41],
            [495, 'Kim Sơn', 'Huyện', 41],
            [496, 'Nho Quan', 'Huyện', 41],
            [497, 'Ninh Bình', 'Thành phố', 41],
            [498, 'Tam Điệp', 'Thị xã', 41],
            [499, 'Yên Khánh', 'Huyện', 41],
            [500, 'Yên Mô', 'Huyện', 41],
            [501, 'Cẩm Khê', 'Huyện', 42],
            [502, 'Đoan Hùng', 'Huyện', 42],
            [503, 'Hạ Hòa', 'Huyện', 42],
            [504, 'Lâm Thao', 'Huyện', 42],
            [505, 'Phù Ninh', 'Huyện', 42],
            [506, 'Phú Thọ', 'Thị xã', 42],
            [507, 'Tam Nông', 'Huyện', 42],
            [508, 'Tân Sơn', 'Huyện', 42],
            [509, 'Thanh Ba', 'Huyện', 42],
            [510, 'Thanh Sơn', 'Huyện', 42],
            [511, 'Thanh Thủy', 'Huyện', 42],
            [512, 'Việt Trì', 'Thành phố', 42],
            [513, 'Yên Lập', 'Huyện', 42],
            [514, 'Bác Ái', 'Huyện', 43],
            [515, 'Ninh Hải', 'Huyện', 43],
            [516, 'Ninh Phước', 'Huyện', 43],
            [517, 'Ninh Sơn', 'Huyện', 43],
            [518, 'Phan Rang - Tháp Chàm', 'Thành phố', 43],
            [519, 'Thuận Bắc', 'Huyện', 43],
            [520, 'Thuận Nam', 'Huyện', 43],
            [521, 'Đông Hòa', 'Huyện', 44],
            [522, 'Đồng Xuân', 'Huyện', 44],
            [523, 'Phú Hòa', 'Huyện', 44],
            [524, 'Sơn Hòa', 'Huyện', 44],
            [525, 'Sông Cầu', 'Thị xã', 44],
            [526, 'Sông Hinh', 'Huyện', 44],
            [527, 'Tây Hòa', 'Huyện', 44],
            [528, 'Tuy An', 'Huyện', 44],
            [529, 'Tuy Hòa', 'Thành phố', 44],
            [530, 'Bình Lục', 'Huyện', 45],
            [531, 'Duy Tiên', 'Huyện', 45],
            [532, 'Kim Bảng', 'Huyện', 45],
            [533, 'Lý Nhân', 'Huyện', 45],
            [534, 'Phủ Lý', 'Thành phố', 45],
            [535, 'Thanh Liêm', 'Huyện', 45],
            [536, 'Cẩm Xuyên', 'Huyện', 46],
            [537, 'Can Lộc', 'Huyện', 46],
            [538, 'Đức Thọ', 'Huyện', 46],
            [539, 'Hà Tĩnh', 'Thành phố', 46],
            [540, 'Hồng Lĩnh', 'Thị xã', 46],
            [541, 'Hương Khê', 'Huyện', 46],
            [542, 'Hương Sơn', 'Huyện', 46],
            [543, 'Kỳ Anh', 'Huyện', 46],
            [544, 'Lộc Hà', 'Huyện', 46],
            [545, 'Nghi Xuân', 'Huyện', 46],
            [546, 'Thạch Hà', 'Huyện', 46],
            [547, 'Vũ Quang', 'Huyện', 46],
            [548, 'Cao Lãnh', 'Thành phố', 47],
            [549, 'Châu Thành', 'Huyện', 47],
            [550, 'Hồng Ngự', 'Thị xã', 47],
            [551, 'Huyện Cao Lãnh', 'Huyện', 47],
            [552, 'Huyện Hồng Ngự', 'Huyện', 47],
            [553, 'Lai Vung', 'Huyện', 47],
            [554, 'Lấp Vò', 'Huyện', 47],
            [555, 'Sa Đéc', 'Thị xã', 47],
            [556, 'Tam Nông', 'Huyện', 47],
            [557, 'Tân Hồng', 'Huyện', 47],
            [558, 'Thanh Bình', 'Huyện', 47],
            [559, 'Tháp Mười', 'Huyện', 47],
            [560, 'Châu Thành', 'Huyện', 48],
            [561, 'Cù Lao Dung', 'Huyện', 48],
            [562, 'Kế Sách', 'Huyện', 48],
            [563, 'Long Phú', 'Huyện', 48],
            [564, 'Mỹ Tú', 'Huyện', 48],
            [565, 'Mỹ Xuyên', 'Huyện', 48],
            [566, 'Ngã Năm', 'Huyện', 48],
            [567, 'Sóc Trăng', 'Thành phố', 48],
            [568, 'Thạnh Trị', 'Huyện', 48],
            [569, 'Trần Đề', 'Huyện', 48],
            [570, 'Vĩnh Châu', 'Huyện', 48],
            [571, 'Đăk Glei', 'Huyện', 49],
            [572, 'Đăk Hà', 'Huyện', 49],
            [573, 'Đăk Tô', 'Huyện', 49],
            [574, 'Ia H\'Drai', 'Huyện', 49],
            [575, 'Kon Plông', 'Huyện', 49],
            [576, 'Kon Rẫy', 'Huyện', 49],
            [577, 'KonTum', 'Thành phố', 49],
            [578, 'Ngọc Hồi', 'Huyện', 49],
            [579, 'Sa Thầy', 'Huyện', 49],
            [580, 'Tu Mơ Rông', 'Huyện', 49],
            [581, 'Ba Đồn', 'Thị xã', 50],
            [582, 'Bố Trạch', 'Huyện', 50],
            [583, 'Đồng Hới', 'Thành phố', 50],
            [584, 'Lệ Thủy', 'Huyện', 50],
            [585, 'Minh Hóa', 'Huyện', 50],
            [586, 'Quảng Ninh', 'Huyện', 50],
            [587, 'Quảng Trạch', 'Huyện', 50],
            [588, 'Tuyên Hóa', 'Huyện', 50],
            [589, 'Cam Lộ', 'Huyện', 51],
            [590, 'Đa Krông', 'Huyện', 51],
            [591, 'Đảo Cồn cỏ', 'Huyện', 51],
            [592, 'Đông Hà', 'Thành phố', 51],
            [593, 'Gio Linh', 'Huyện', 51],
            [594, 'Hải Lăng', 'Huyện', 51],
            [595, 'Hướng Hóa', 'Huyện', 51],
            [596, 'Quảng Trị', 'Thị xã', 51],
            [597, 'Triệu Phong', 'Huyện', 51],
            [598, 'Vĩnh Linh', 'Huyện', 51],
            [599, 'Càng Long', 'Huyện', 52],
            [600, 'Cầu Kè', 'Huyện', 52],
            [601, 'Cầu Ngang', 'Huyện', 52],
            [602, 'Châu Thành', 'Huyện', 52],
            [603, 'Duyên Hải', 'Huyện', 52],
            [604, 'Tiểu Cần', 'Huyện', 52],
            [605, 'Trà Cú', 'Huyện', 52],
            [606, 'Trà Vinh', 'Thành phố', 52],
            [607, 'Châu Thành', 'Huyện', 53],
            [608, 'Châu Thành A', 'Huyện', 53],
            [609, 'Long Mỹ', 'Huyện', 53],
            [610, 'Ngã Bảy', 'Thị xã', 53],
            [611, 'Phụng Hiệp', 'Huyện', 53],
            [612, 'Vị Thanh', 'Thành phố', 53],
            [613, 'Vị Thủy', 'Huyện', 53],
            [614, 'Bắc Yên', 'Huyện', 54],
            [615, 'Mai Sơn', 'Huyện', 54],
            [616, 'Mộc Châu', 'Huyện', 54],
            [617, 'Mường La', 'Huyện', 54],
            [618, 'Phù Yên', 'Huyện', 54],
            [619, 'Quỳnh Nhai', 'Huyện', 54],
            [620, 'Sơn La', 'Thành phố', 54],
            [621, 'Sông Mã', 'Huyện', 54],
            [622, 'Sốp Cộp', 'Huyện', 54],
            [623, 'Thuận Châu', 'Huyện', 54],
            [624, 'Vân Hồ', 'Huyện', 54],
            [625, 'Yên Châu', 'Huyện', 54],
            [626, 'Bạc Liêu', 'Thành phố', 55],
            [627, 'Đông Hải', 'Huyện', 55],
            [628, 'Giá Rai', 'Huyện', 55],
            [629, 'Hòa Bình', 'Huyện', 55],
            [630, 'Hồng Dân', 'Huyện', 55],
            [631, 'Phước Long', 'Huyện', 55],
            [632, 'Vĩnh Lợi', 'Huyện', 55],
            [633, 'Lục Yên', 'Huyện', 56],
            [634, 'Mù Cang Chải', 'Huyện', 56],
            [635, 'Nghĩa Lộ', 'Thị xã', 56],
            [636, 'Trạm Tấu', 'Huyện', 56],
            [637, 'Trấn Yên', 'Huyện', 56],
            [638, 'Văn Chấn', 'Huyện', 56],
            [639, 'Văn Yên', 'Huyện', 56],
            [640, 'Yên Bái', 'Thành phố', 56],
            [641, 'Yên Bình', 'Huyện', 56],
            [642, 'Chiêm Hóa', 'Huyện', 57],
            [643, 'Hàm Yên', 'Huyện', 57],
            [644, 'Lâm Bình', 'Huyện', 57],
            [645, 'Na Hang', 'Huyện', 57],
            [646, 'Sơn Dương', 'Huyện', 57],
            [647, 'Tuyên Quang', 'Thành phố', 57],
            [648, 'Yên Sơn', 'Huyện', 57],
            [649, 'Điện Biên', 'Huyện', 58],
            [650, 'Điện Biên Đông', 'Huyện', 58],
            [651, 'Điện Biên Phủ', 'Thành phố', 58],
            [652, 'Mường Ảng', 'Huyện', 58],
            [653, 'Mường Chà', 'Huyện', 58],
            [654, 'Mường Lay', 'Thị xã', 58],
            [655, 'Mường Nhé', 'Huyện', 58],
            [656, 'Nậm Pồ', 'Huyện', 58],
            [657, 'Tủa Chùa', 'Huyện', 58],
            [658, 'Tuần Giáo', 'Huyện', 58],
            [659, 'Lai Châu', 'Thị xã', 59],
            [660, 'Mường Tè', 'Huyện', 59],
            [661, 'Nậm Nhùn', 'Huyện', 59],
            [662, 'Phong Thổ', 'Huyện', 59],
            [663, 'Sìn Hồ', 'Huyện', 59],
            [664, 'Tam Đường', 'Huyện', 59],
            [665, 'Tân Uyên', 'Huyện', 59],
            [666, 'Than Uyên', 'Huyện', 59],
            [667, 'Bắc Sơn', 'Huyện', 60],
            [668, 'Bình Gia', 'Huyện', 60],
            [669, 'Cao Lộc', 'Huyện', 60],
            [670, 'Chi Lăng', 'Huyện', 60],
            [671, 'Đình Lập', 'Huyện', 60],
            [672, 'Hữu Lũng', 'Huyện', 60],
            [673, 'Lạng Sơn', 'Thành phố', 60],
            [674, 'Lộc Bình', 'Huyện', 60],
            [675, 'Tràng Định', 'Huyện', 60],
            [676, 'Văn Lãng', 'Huyện', 60],
            [677, 'Văn Quan', 'Huyện', 60],
            [678, 'Bắc Mê', 'Huyện', 61],
            [679, 'Bắc Quang', 'Huyện', 61],
            [680, 'Đồng Văn', 'Huyện', 61],
            [681, 'Hà Giang', 'Thành phố', 61],
            [682, 'Hoàng Su Phì', 'Huyện', 61],
            [683, 'Mèo Vạc', 'Huyện', 61],
            [684, 'Quản Bạ', 'Huyện', 61],
            [685, 'Quang Bình', 'Huyện', 61],
            [686, 'Vị Xuyên', 'Huyện', 61],
            [687, 'Xín Mần', 'Huyện', 61],
            [688, 'Yên Minh', 'Huyện', 61],
            [689, 'Ba Bể', 'Huyện', 62],
            [690, 'Bắc Kạn', 'Thị xã', 62],
            [691, 'Bạch Thông', 'Huyện', 62],
            [692, 'Chợ Đồn', 'Huyện', 62],
            [693, 'Chợ Mới', 'Huyện', 62],
            [694, 'Na Rì', 'Huyện', 62],
            [695, 'Ngân Sơn', 'Huyện', 62],
            [696, 'Pác Nặm', 'Huyện', 62],
            [697, 'Bảo Lạc', 'Huyện', 63],
            [698, 'Bảo Lâm', 'Huyện', 63],
            [699, 'Cao Bằng', 'Thị xã', 63],
            [700, 'Hạ Lang', 'Huyện', 63],
            [701, 'Hà Quảng', 'Huyện', 63],
            [702, 'Hòa An', 'Huyện', 63],
            [703, 'Nguyên Bình', 'Huyện', 63],
            [704, 'Phục Hòa', 'Huyện', 63],
            [705, 'Quảng Uyên', 'Huyện', 63],
            [706, 'Thạch An', 'Huyện', 63],
            [707, 'Thông Nông', 'Huyện', 63],
            [708, 'Trà Lĩnh', 'Huyện', 63],
            [709, 'Trùng Khánh', 'Huyện', 63]
        ];
    }
}
